/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as ManifestoRouteImport } from './routes/manifesto'
import { Route as ImportRouteImport } from './routes/import'
import { Route as CreateRouteImport } from './routes/create'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WalletIndexRouteImport } from './routes/wallet.index'
import { Route as WalletWifAddRouteImport } from './routes/wallet.wif-add'
import { Route as WalletWatchAddRouteImport } from './routes/wallet.watch-add'
import { Route as WalletSettingsRouteImport } from './routes/wallet.settings'
import { Route as WalletSendRouteImport } from './routes/wallet.send'
import { Route as WalletReceiveRouteImport } from './routes/wallet.receive'
import { Route as WalletContactsRouteImport } from './routes/wallet.contacts'
import { Route as WalletBackupRouteImport } from './routes/wallet.backup'
import { Route as PayInvoiceIdRouteImport } from './routes/pay.$invoiceId'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as WalletLtcSendRouteImport } from './routes/wallet.ltc.send'
import { Route as WalletLtcReceiveRouteImport } from './routes/wallet.ltc.receive'
import { Route as WalletIskSendRouteImport } from './routes/wallet.isk.send'
import { Route as WalletIskReceiveRouteImport } from './routes/wallet.isk.receive'
import { Route as WalletEvmChainRouteImport } from './routes/wallet.evm.$chain'
import { Route as WalletDogeSendRouteImport } from './routes/wallet.doge.send'
import { Route as WalletDogeReceiveRouteImport } from './routes/wallet.doge.receive'
import { Route as ApiEvmChainRouteImport } from './routes/api/evm.$chain'
import { Route as WalletWifIdSendRouteImport } from './routes/wallet.wif.$id.send'
import { Route as WalletWifIdReceiveRouteImport } from './routes/wallet.wif.$id.receive'
import { Route as WalletEvmChainSwapRouteImport } from './routes/wallet.evm.$chain.swap'
import { Route as WalletEvmChainSendRouteImport } from './routes/wallet.evm.$chain.send'
import { Route as WalletEvmChainReceiveRouteImport } from './routes/wallet.evm.$chain.receive'
import { Route as ApiNectarPayInvoiceIdRouteImport } from './routes/api/nectar.pay.$invoiceId'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestoRoute = ManifestoRouteImport.update({
  id: '/manifesto',
  path: '/manifesto',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletIndexRoute = WalletIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WalletRoute,
} as any)
const WalletWifAddRoute = WalletWifAddRouteImport.update({
  id: '/wif-add',
  path: '/wif-add',
  getParentRoute: () => WalletRoute,
} as any)
const WalletWatchAddRoute = WalletWatchAddRouteImport.update({
  id: '/watch-add',
  path: '/watch-add',
  getParentRoute: () => WalletRoute,
} as any)
const WalletSettingsRoute = WalletSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => WalletRoute,
} as any)
const WalletSendRoute = WalletSendRouteImport.update({
  id: '/send',
  path: '/send',
  getParentRoute: () => WalletRoute,
} as any)
const WalletReceiveRoute = WalletReceiveRouteImport.update({
  id: '/receive',
  path: '/receive',
  getParentRoute: () => WalletRoute,
} as any)
const WalletContactsRoute = WalletContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => WalletRoute,
} as any)
const WalletBackupRoute = WalletBackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => WalletRoute,
} as any)
const PayInvoiceIdRoute = PayInvoiceIdRouteImport.update({
  id: '/pay/$invoiceId',
  path: '/pay/$invoiceId',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletLtcSendRoute = WalletLtcSendRouteImport.update({
  id: '/ltc/send',
  path: '/ltc/send',
  getParentRoute: () => WalletRoute,
} as any)
const WalletLtcReceiveRoute = WalletLtcReceiveRouteImport.update({
  id: '/ltc/receive',
  path: '/ltc/receive',
  getParentRoute: () => WalletRoute,
} as any)
const WalletIskSendRoute = WalletIskSendRouteImport.update({
  id: '/isk/send',
  path: '/isk/send',
  getParentRoute: () => WalletRoute,
} as any)
const WalletIskReceiveRoute = WalletIskReceiveRouteImport.update({
  id: '/isk/receive',
  path: '/isk/receive',
  getParentRoute: () => WalletRoute,
} as any)
const WalletEvmChainRoute = WalletEvmChainRouteImport.update({
  id: '/evm/$chain',
  path: '/evm/$chain',
  getParentRoute: () => WalletRoute,
} as any)
const WalletDogeSendRoute = WalletDogeSendRouteImport.update({
  id: '/doge/send',
  path: '/doge/send',
  getParentRoute: () => WalletRoute,
} as any)
const WalletDogeReceiveRoute = WalletDogeReceiveRouteImport.update({
  id: '/doge/receive',
  path: '/doge/receive',
  getParentRoute: () => WalletRoute,
} as any)
const ApiEvmChainRoute = ApiEvmChainRouteImport.update({
  id: '/api/evm/$chain',
  path: '/api/evm/$chain',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletWifIdSendRoute = WalletWifIdSendRouteImport.update({
  id: '/wif/$id/send',
  path: '/wif/$id/send',
  getParentRoute: () => WalletRoute,
} as any)
const WalletWifIdReceiveRoute = WalletWifIdReceiveRouteImport.update({
  id: '/wif/$id/receive',
  path: '/wif/$id/receive',
  getParentRoute: () => WalletRoute,
} as any)
const WalletEvmChainSwapRoute = WalletEvmChainSwapRouteImport.update({
  id: '/swap',
  path: '/swap',
  getParentRoute: () => WalletEvmChainRoute,
} as any)
const WalletEvmChainSendRoute = WalletEvmChainSendRouteImport.update({
  id: '/send',
  path: '/send',
  getParentRoute: () => WalletEvmChainRoute,
} as any)
const WalletEvmChainReceiveRoute = WalletEvmChainReceiveRouteImport.update({
  id: '/receive',
  path: '/receive',
  getParentRoute: () => WalletEvmChainRoute,
} as any)
const ApiNectarPayInvoiceIdRoute = ApiNectarPayInvoiceIdRouteImport.update({
  id: '/api/nectar/pay/$invoiceId',
  path: '/api/nectar/pay/$invoiceId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/import': typeof ImportRoute
  '/manifesto': typeof ManifestoRoute
  '/wallet': typeof WalletRouteWithChildren
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/pay/$invoiceId': typeof PayInvoiceIdRoute
  '/wallet/backup': typeof WalletBackupRoute
  '/wallet/contacts': typeof WalletContactsRoute
  '/wallet/receive': typeof WalletReceiveRoute
  '/wallet/send': typeof WalletSendRoute
  '/wallet/settings': typeof WalletSettingsRoute
  '/wallet/watch-add': typeof WalletWatchAddRoute
  '/wallet/wif-add': typeof WalletWifAddRoute
  '/wallet/': typeof WalletIndexRoute
  '/api/evm/$chain': typeof ApiEvmChainRoute
  '/wallet/doge/receive': typeof WalletDogeReceiveRoute
  '/wallet/doge/send': typeof WalletDogeSendRoute
  '/wallet/evm/$chain': typeof WalletEvmChainRouteWithChildren
  '/wallet/isk/receive': typeof WalletIskReceiveRoute
  '/wallet/isk/send': typeof WalletIskSendRoute
  '/wallet/ltc/receive': typeof WalletLtcReceiveRoute
  '/wallet/ltc/send': typeof WalletLtcSendRoute
  '/api/nectar/pay/$invoiceId': typeof ApiNectarPayInvoiceIdRoute
  '/wallet/evm/$chain/receive': typeof WalletEvmChainReceiveRoute
  '/wallet/evm/$chain/send': typeof WalletEvmChainSendRoute
  '/wallet/evm/$chain/swap': typeof WalletEvmChainSwapRoute
  '/wallet/wif/$id/receive': typeof WalletWifIdReceiveRoute
  '/wallet/wif/$id/send': typeof WalletWifIdSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/import': typeof ImportRoute
  '/manifesto': typeof ManifestoRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/pay/$invoiceId': typeof PayInvoiceIdRoute
  '/wallet/backup': typeof WalletBackupRoute
  '/wallet/contacts': typeof WalletContactsRoute
  '/wallet/receive': typeof WalletReceiveRoute
  '/wallet/send': typeof WalletSendRoute
  '/wallet/settings': typeof WalletSettingsRoute
  '/wallet/watch-add': typeof WalletWatchAddRoute
  '/wallet/wif-add': typeof WalletWifAddRoute
  '/wallet': typeof WalletIndexRoute
  '/api/evm/$chain': typeof ApiEvmChainRoute
  '/wallet/doge/receive': typeof WalletDogeReceiveRoute
  '/wallet/doge/send': typeof WalletDogeSendRoute
  '/wallet/evm/$chain': typeof WalletEvmChainRouteWithChildren
  '/wallet/isk/receive': typeof WalletIskReceiveRoute
  '/wallet/isk/send': typeof WalletIskSendRoute
  '/wallet/ltc/receive': typeof WalletLtcReceiveRoute
  '/wallet/ltc/send': typeof WalletLtcSendRoute
  '/api/nectar/pay/$invoiceId': typeof ApiNectarPayInvoiceIdRoute
  '/wallet/evm/$chain/receive': typeof WalletEvmChainReceiveRoute
  '/wallet/evm/$chain/send': typeof WalletEvmChainSendRoute
  '/wallet/evm/$chain/swap': typeof WalletEvmChainSwapRoute
  '/wallet/wif/$id/receive': typeof WalletWifIdReceiveRoute
  '/wallet/wif/$id/send': typeof WalletWifIdSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/import': typeof ImportRoute
  '/manifesto': typeof ManifestoRoute
  '/wallet': typeof WalletRouteWithChildren
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/pay/$invoiceId': typeof PayInvoiceIdRoute
  '/wallet/backup': typeof WalletBackupRoute
  '/wallet/contacts': typeof WalletContactsRoute
  '/wallet/receive': typeof WalletReceiveRoute
  '/wallet/send': typeof WalletSendRoute
  '/wallet/settings': typeof WalletSettingsRoute
  '/wallet/watch-add': typeof WalletWatchAddRoute
  '/wallet/wif-add': typeof WalletWifAddRoute
  '/wallet/': typeof WalletIndexRoute
  '/api/evm/$chain': typeof ApiEvmChainRoute
  '/wallet/doge/receive': typeof WalletDogeReceiveRoute
  '/wallet/doge/send': typeof WalletDogeSendRoute
  '/wallet/evm/$chain': typeof WalletEvmChainRouteWithChildren
  '/wallet/isk/receive': typeof WalletIskReceiveRoute
  '/wallet/isk/send': typeof WalletIskSendRoute
  '/wallet/ltc/receive': typeof WalletLtcReceiveRoute
  '/wallet/ltc/send': typeof WalletLtcSendRoute
  '/api/nectar/pay/$invoiceId': typeof ApiNectarPayInvoiceIdRoute
  '/wallet/evm/$chain/receive': typeof WalletEvmChainReceiveRoute
  '/wallet/evm/$chain/send': typeof WalletEvmChainSendRoute
  '/wallet/evm/$chain/swap': typeof WalletEvmChainSwapRoute
  '/wallet/wif/$id/receive': typeof WalletWifIdReceiveRoute
  '/wallet/wif/$id/send': typeof WalletWifIdSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create'
    | '/import'
    | '/manifesto'
    | '/wallet'
    | '/legal/privacy'
    | '/legal/terms'
    | '/pay/$invoiceId'
    | '/wallet/backup'
    | '/wallet/contacts'
    | '/wallet/receive'
    | '/wallet/send'
    | '/wallet/settings'
    | '/wallet/watch-add'
    | '/wallet/wif-add'
    | '/wallet/'
    | '/api/evm/$chain'
    | '/wallet/doge/receive'
    | '/wallet/doge/send'
    | '/wallet/evm/$chain'
    | '/wallet/isk/receive'
    | '/wallet/isk/send'
    | '/wallet/ltc/receive'
    | '/wallet/ltc/send'
    | '/api/nectar/pay/$invoiceId'
    | '/wallet/evm/$chain/receive'
    | '/wallet/evm/$chain/send'
    | '/wallet/evm/$chain/swap'
    | '/wallet/wif/$id/receive'
    | '/wallet/wif/$id/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create'
    | '/import'
    | '/manifesto'
    | '/legal/privacy'
    | '/legal/terms'
    | '/pay/$invoiceId'
    | '/wallet/backup'
    | '/wallet/contacts'
    | '/wallet/receive'
    | '/wallet/send'
    | '/wallet/settings'
    | '/wallet/watch-add'
    | '/wallet/wif-add'
    | '/wallet'
    | '/api/evm/$chain'
    | '/wallet/doge/receive'
    | '/wallet/doge/send'
    | '/wallet/evm/$chain'
    | '/wallet/isk/receive'
    | '/wallet/isk/send'
    | '/wallet/ltc/receive'
    | '/wallet/ltc/send'
    | '/api/nectar/pay/$invoiceId'
    | '/wallet/evm/$chain/receive'
    | '/wallet/evm/$chain/send'
    | '/wallet/evm/$chain/swap'
    | '/wallet/wif/$id/receive'
    | '/wallet/wif/$id/send'
  id:
    | '__root__'
    | '/'
    | '/create'
    | '/import'
    | '/manifesto'
    | '/wallet'
    | '/legal/privacy'
    | '/legal/terms'
    | '/pay/$invoiceId'
    | '/wallet/backup'
    | '/wallet/contacts'
    | '/wallet/receive'
    | '/wallet/send'
    | '/wallet/settings'
    | '/wallet/watch-add'
    | '/wallet/wif-add'
    | '/wallet/'
    | '/api/evm/$chain'
    | '/wallet/doge/receive'
    | '/wallet/doge/send'
    | '/wallet/evm/$chain'
    | '/wallet/isk/receive'
    | '/wallet/isk/send'
    | '/wallet/ltc/receive'
    | '/wallet/ltc/send'
    | '/api/nectar/pay/$invoiceId'
    | '/wallet/evm/$chain/receive'
    | '/wallet/evm/$chain/send'
    | '/wallet/evm/$chain/swap'
    | '/wallet/wif/$id/receive'
    | '/wallet/wif/$id/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateRoute: typeof CreateRoute
  ImportRoute: typeof ImportRoute
  ManifestoRoute: typeof ManifestoRoute
  WalletRoute: typeof WalletRouteWithChildren
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
  PayInvoiceIdRoute: typeof PayInvoiceIdRoute
  ApiEvmChainRoute: typeof ApiEvmChainRoute
  ApiNectarPayInvoiceIdRoute: typeof ApiNectarPayInvoiceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifesto': {
      id: '/manifesto'
      path: '/manifesto'
      fullPath: '/manifesto'
      preLoaderRoute: typeof ManifestoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet/': {
      id: '/wallet/'
      path: '/'
      fullPath: '/wallet/'
      preLoaderRoute: typeof WalletIndexRouteImport
      parentRoute: typeof WalletRoute
    }
    '/wallet/wif-add': {
      id: '/wallet/wif-add'
      path: '/wif-add'
      fullPath: '/wallet/wif-add'
      preLoaderRoute: typeof WalletWifAddRouteImport
      parentRoute: typeof WalletRoute
    }
    '/wallet/watch-add': {
      id: '/wallet/watch-add'
      path: '/watch-add'
      fullPath: '/wallet/watch-add'
      preLoaderRoute: typeof WalletWatchAddRouteImport
      parentRoute: typeof WalletRoute
    }
    '/wallet/settings': {
      id: '/wallet/settings'
      path: '/settings'
      fullPath: '/wallet/settings'
      preLoaderRoute: typeof WalletSettingsRouteImport
      parentRoute: typeof WalletRoute
    }
    '/wallet/send': {
      id: '/wallet/send'
      path: '/send'
      fullPath: '/wallet/send'
      preLoaderRoute: typeof WalletSendRouteImport
      parentRoute: typeof WalletRoute
    }
    '/wallet/receive': {
      id: '/wallet/receive'
      path: '/receive'
      fullPath: '/wallet/receive'
      preLoaderRoute: typeof WalletReceiveRouteImport
      parentRoute: typeof WalletRoute
    }
    '/wallet/contacts': {
      id: '/wallet/contacts'
      path: '/contacts'
      fullPath: '/wallet/contacts'
      preLoaderRoute: typeof WalletContactsRouteImport
      parentRoute: typeof WalletRoute
    }
    '/wallet/backup': {
      id: '/wallet/backup'
      path: '/backup'
      fullPath: '/wallet/backup'
      preLoaderRoute: typeof WalletBackupRouteImport
      parentRoute: typeof WalletRoute
    }
    '/pay/$invoiceId': {
      id: '/pay/$invoiceId'
      path: '/pay/$invoiceId'
      fullPath: '/pay/$invoiceId'
      preLoaderRoute: typeof PayInvoiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet/ltc/send': {
      id: '/wallet/ltc/send'
      path: '/ltc/send'
      fullPath: '/wallet/ltc/send'
      preLoaderRoute: typeof WalletLtcSendRouteImport
      parentRoute: typeof WalletRoute
    }
    '/wallet/ltc/receive': {
      id: '/wallet/ltc/receive'
      path: '/ltc/receive'
      fullPath: '/wallet/ltc/receive'
      preLoaderRoute: typeof WalletLtcReceiveRouteImport
      parentRoute: typeof WalletRoute
    }
    '/wallet/isk/send': {
      id: '/wallet/isk/send'
      path: '/isk/send'
      fullPath: '/wallet/isk/send'
      preLoaderRoute: typeof WalletIskSendRouteImport
      parentRoute: typeof WalletRoute
    }
    '/wallet/isk/receive': {
      id: '/wallet/isk/receive'
      path: '/isk/receive'
      fullPath: '/wallet/isk/receive'
      preLoaderRoute: typeof WalletIskReceiveRouteImport
      parentRoute: typeof WalletRoute
    }
    '/wallet/evm/$chain': {
      id: '/wallet/evm/$chain'
      path: '/evm/$chain'
      fullPath: '/wallet/evm/$chain'
      preLoaderRoute: typeof WalletEvmChainRouteImport
      parentRoute: typeof WalletRoute
    }
    '/wallet/doge/send': {
      id: '/wallet/doge/send'
      path: '/doge/send'
      fullPath: '/wallet/doge/send'
      preLoaderRoute: typeof WalletDogeSendRouteImport
      parentRoute: typeof WalletRoute
    }
    '/wallet/doge/receive': {
      id: '/wallet/doge/receive'
      path: '/doge/receive'
      fullPath: '/wallet/doge/receive'
      preLoaderRoute: typeof WalletDogeReceiveRouteImport
      parentRoute: typeof WalletRoute
    }
    '/api/evm/$chain': {
      id: '/api/evm/$chain'
      path: '/api/evm/$chain'
      fullPath: '/api/evm/$chain'
      preLoaderRoute: typeof ApiEvmChainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet/wif/$id/send': {
      id: '/wallet/wif/$id/send'
      path: '/wif/$id/send'
      fullPath: '/wallet/wif/$id/send'
      preLoaderRoute: typeof WalletWifIdSendRouteImport
      parentRoute: typeof WalletRoute
    }
    '/wallet/wif/$id/receive': {
      id: '/wallet/wif/$id/receive'
      path: '/wif/$id/receive'
      fullPath: '/wallet/wif/$id/receive'
      preLoaderRoute: typeof WalletWifIdReceiveRouteImport
      parentRoute: typeof WalletRoute
    }
    '/wallet/evm/$chain/swap': {
      id: '/wallet/evm/$chain/swap'
      path: '/swap'
      fullPath: '/wallet/evm/$chain/swap'
      preLoaderRoute: typeof WalletEvmChainSwapRouteImport
      parentRoute: typeof WalletEvmChainRoute
    }
    '/wallet/evm/$chain/send': {
      id: '/wallet/evm/$chain/send'
      path: '/send'
      fullPath: '/wallet/evm/$chain/send'
      preLoaderRoute: typeof WalletEvmChainSendRouteImport
      parentRoute: typeof WalletEvmChainRoute
    }
    '/wallet/evm/$chain/receive': {
      id: '/wallet/evm/$chain/receive'
      path: '/receive'
      fullPath: '/wallet/evm/$chain/receive'
      preLoaderRoute: typeof WalletEvmChainReceiveRouteImport
      parentRoute: typeof WalletEvmChainRoute
    }
    '/api/nectar/pay/$invoiceId': {
      id: '/api/nectar/pay/$invoiceId'
      path: '/api/nectar/pay/$invoiceId'
      fullPath: '/api/nectar/pay/$invoiceId'
      preLoaderRoute: typeof ApiNectarPayInvoiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface WalletEvmChainRouteChildren {
  WalletEvmChainReceiveRoute: typeof WalletEvmChainReceiveRoute
  WalletEvmChainSendRoute: typeof WalletEvmChainSendRoute
  WalletEvmChainSwapRoute: typeof WalletEvmChainSwapRoute
}

const WalletEvmChainRouteChildren: WalletEvmChainRouteChildren = {
  WalletEvmChainReceiveRoute: WalletEvmChainReceiveRoute,
  WalletEvmChainSendRoute: WalletEvmChainSendRoute,
  WalletEvmChainSwapRoute: WalletEvmChainSwapRoute,
}

const WalletEvmChainRouteWithChildren = WalletEvmChainRoute._addFileChildren(
  WalletEvmChainRouteChildren,
)

interface WalletRouteChildren {
  WalletBackupRoute: typeof WalletBackupRoute
  WalletContactsRoute: typeof WalletContactsRoute
  WalletReceiveRoute: typeof WalletReceiveRoute
  WalletSendRoute: typeof WalletSendRoute
  WalletSettingsRoute: typeof WalletSettingsRoute
  WalletWatchAddRoute: typeof WalletWatchAddRoute
  WalletWifAddRoute: typeof WalletWifAddRoute
  WalletIndexRoute: typeof WalletIndexRoute
  WalletDogeReceiveRoute: typeof WalletDogeReceiveRoute
  WalletDogeSendRoute: typeof WalletDogeSendRoute
  WalletEvmChainRoute: typeof WalletEvmChainRouteWithChildren
  WalletIskReceiveRoute: typeof WalletIskReceiveRoute
  WalletIskSendRoute: typeof WalletIskSendRoute
  WalletLtcReceiveRoute: typeof WalletLtcReceiveRoute
  WalletLtcSendRoute: typeof WalletLtcSendRoute
  WalletWifIdReceiveRoute: typeof WalletWifIdReceiveRoute
  WalletWifIdSendRoute: typeof WalletWifIdSendRoute
}

const WalletRouteChildren: WalletRouteChildren = {
  WalletBackupRoute: WalletBackupRoute,
  WalletContactsRoute: WalletContactsRoute,
  WalletReceiveRoute: WalletReceiveRoute,
  WalletSendRoute: WalletSendRoute,
  WalletSettingsRoute: WalletSettingsRoute,
  WalletWatchAddRoute: WalletWatchAddRoute,
  WalletWifAddRoute: WalletWifAddRoute,
  WalletIndexRoute: WalletIndexRoute,
  WalletDogeReceiveRoute: WalletDogeReceiveRoute,
  WalletDogeSendRoute: WalletDogeSendRoute,
  WalletEvmChainRoute: WalletEvmChainRouteWithChildren,
  WalletIskReceiveRoute: WalletIskReceiveRoute,
  WalletIskSendRoute: WalletIskSendRoute,
  WalletLtcReceiveRoute: WalletLtcReceiveRoute,
  WalletLtcSendRoute: WalletLtcSendRoute,
  WalletWifIdReceiveRoute: WalletWifIdReceiveRoute,
  WalletWifIdSendRoute: WalletWifIdSendRoute,
}

const WalletRouteWithChildren =
  WalletRoute._addFileChildren(WalletRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateRoute: CreateRoute,
  ImportRoute: ImportRoute,
  ManifestoRoute: ManifestoRoute,
  WalletRoute: WalletRouteWithChildren,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
  PayInvoiceIdRoute: PayInvoiceIdRoute,
  ApiEvmChainRoute: ApiEvmChainRoute,
  ApiNectarPayInvoiceIdRoute: ApiNectarPayInvoiceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
